---
services:
  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  python:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/app
volumes:
  db:
